const defaultPlans = [
    {
        name: 'Free',
        slug: 'free',
        price: 0,
        currency: 'INR',
        billingPeriod: 'free',
        durationDays: 0,
        deviceLimit: 1,
        maxPhotos: 100,
        cloudinaryPhotoLimit: 0,
        cloudinaryVideoLimit: 0,
        features: ['Basic monitoring', '1 device', 'Screen view', 'Camera view', '100 photos gallery'],
        description: 'Get started with basic monitoring',
        isActive: true,
        isPopular: false,
        sortOrder: 0,
    },
    {
        name: 'Weekly',
        slug: 'weekly',
        price: 90,
        currency: 'INR',
        billingPeriod: 'weekly',
        durationDays: 7,
        deviceLimit: 2,
        maxPhotos: 1000,
        cloudinaryPhotoLimit: 0,
        cloudinaryVideoLimit: 0,
        features: ['All Free features', '2 devices', 'Live activity', 'Chat monitoring', 'Gallery access', '1000 photos'],
        description: 'Flexible access for one week',
        isActive: true,
        isPopular: false,
        sortOrder: 1,
    },
    {
        name: '15 Days',
        slug: 'fifteen-days',
        price: 180,
        currency: 'INR',
        billingPeriod: 'custom',
        durationDays: 15,
        deviceLimit: 2,
        maxPhotos: 1000,
        cloudinaryPhotoLimit: 0,
        cloudinaryVideoLimit: 0,
        features: ['All Free features', '2 devices', 'Live activity', 'Chat monitoring', 'Gallery access', '1000 photos'],
        description: 'Flexible access for fifteen days',
        isActive: true,
        isPopular: false,
        sortOrder: 2,
    },
    {
        name: 'Monthly',
        slug: 'monthly',
        price: 340,
        currency: 'INR',
        billingPeriod: 'monthly',
        durationDays: 30,
        deviceLimit: 3,
        maxPhotos: 5000,
        cloudinaryPhotoLimit: 500,
        cloudinaryVideoLimit: 50,
        features: ['All 15 Days features', '3 devices', 'Priority support', 'Call recording', 'Website blocking', '5000 photos', '500 cloud photos', '50 cloud videos'],
        description: 'Most popular plan for parents',
        isActive: true,
        isPopular: true,
        sortOrder: 3,
    },
    {
        name: 'Half-Yearly',
        slug: 'half-yearly',
        price: 1300,
        currency: 'INR',
        billingPeriod: 'half-yearly',
        durationDays: 180,
        deviceLimit: 10,
        maxPhotos: 10000,
        cloudinaryPhotoLimit: 5000,
        cloudinaryVideoLimit: 500,
        features: ['All Monthly features', '10 devices', 'VIP support', 'All features unlocked', 'Advanced analytics', '10000 photos', '5000 cloud photos', '500 cloud videos'],
        description: 'Long-term family protection for six months',
        isActive: true,
        isPopular: false,
        sortOrder: 4,
    },
    {
        name: 'Yearly',
        slug: 'yearly',
        price: 1999,
        currency: 'INR',
        billingPeriod: 'yearly',
        durationDays: 365,
        deviceLimit: 15,
        maxPhotos: 99999,
        cloudinaryPhotoLimit: 99999,
        cloudinaryVideoLimit: 99999,
        features: ['All Half-Yearly features', '15 devices', 'VIP support', 'All features unlocked', 'Best yearly value', 'Unlimited photos', 'Unlimited cloud storage'],
        description: 'Best value for a full year of monitoring',
        isActive: true,
        isPopular: false,
        sortOrder: 5,
    },
];

module.exports = defaultPlans;
